### ISSUE TITLE
data-fetch library.... How about "React Query"? 

### ISSUE THREAD

**Issue by soonmac** [chingu-voyages/v39-geckos-team-07#27]
We need to call our API and decide how to manage the data. 
I think it would be convenient to use a library.
I recommend React Query.
React Query is simple.

React Query DOC : 
https://react-query.tanstack.com/devtools
React Query Related Korean article(I wrote it...):
https://velog.io/@soonmac/React-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%BF%BC%EB%A6%AC#%EC%B0%B8%EA%B3%A0

**Comment by loco-co** [comment]
I've read those two articles. Found it helps us fetch data and check them.
I used to console log to check fetched data., but it would be convenient.
Let's use it.
